In [2]:
import pandas as pd
rating = pd.read_csv('ratings.csv')
rating.head()

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [16]:
rating_five = rating[ rating.rating == 5 ]
rating_five.head()

   userId  movieId  rating  timestamp
3       1       47     5.0  964983815
4       1       50     5.0  964982931
6       1      101     5.0  964980868
8       1      151     5.0  964984041
9       1      157     5.0  964984100

In [40]:
rating_five = rating[['movieId', 'rating']][ rating.rating == 5 ]
rating_five.head()

   movieId  rating
3       47     5.0
4       50     5.0
6      101     5.0
8      151     5.0
9      157     5.0

In [42]:
movies = pd.read_csv('movies.csv')
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [46]:
rating_five.groupby('movieId').count().sort_values('rating', ascending=False).merge(movies, on='movieId', how='left').head(1)

   movieId  rating                             title       genres
0      318     153  Shawshank Redemption, The (1994)  Crime|Drama

In [26]:
joined = rating_five.merge(movies, on='movieId', how='left')
joined.head()

,userId,movieId,rating,timestamp,title,genres
0,1,47,5.0,964983815,Seven (a.k.a. Se7en) (1995),Mystery|Thriller
1,1,50,5.0,964982931,"Usual Suspects, The (1995)",Crime|Mystery|Thriller
2,1,101,5.0,964980868,Bottle Rocket (1996),Adventure|Comedy|Crime|Romance
3,1,151,5.0,964984041,Rob Roy (1995),Action|Drama|Romance|War
4,1,157,5.0,964984100,Canadian Bacon (1995),Comedy|War

In [28]:
rating_five.groupby('movieId').count().sort_values('userId', ascending=False).merge(movies, on='movieId', how='left').head()

,movieId,userId,rating,timestamp,title,genres
0,318,153,153,153,"Shawshank Redemption, The (1994)",Crime|Drama
1,296,123,123,123,Pulp Fiction (1994),Comedy|Crime|Drama|Thriller
2,356,116,116,116,Forrest Gump (1994),Comedy|Drama|Romance|War
3,2571,109,109,109,"Matrix, The (1999)",Action|Sci-Fi|Thriller
4,260,104,104,104,Star Wars: Episode IV - A New Hope (1977),Action|Adventure|Sci-Fi

**Задание 2**

По данным файла power.csv посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 год. Не учитывайте в расчётах отрицательные значения quantity.

In [56]:
power = pd.read_csv('power.csv')
power.head()

   country  year  quantity  category
0  Austria  1996       5.0         1
1  Austria  1995      17.0         1
2  Belgium  2014       0.0         1
3  Belgium  2013       0.0         1
4  Belgium  2012      35.0         1

In [64]:
power_filtered = power[ 
    ((power['country'] == 'Latvia') | (power['country'] == 'Lithuania') | (power['country'] == 'Estonia')) & 
    ((power['category'] == 4) | (power['category'] == 12) | (power['category'] == 21)) &
    (power['quantity'] > 0) &
    ((power['year'] >= 2005) & (power['year'] <= 2010))
]
power_filtered.head()

         country  year  quantity  category
10617    Estonia  2008       1.0         4
10620    Estonia  2005       1.0         4
11156  Lithuania  2008       1.0         4
11158  Lithuania  2006       1.0         4
11159  Lithuania  2005       1.0         4

In [67]:
power_filtered['category'].unique()

array([ 4, 12, 21])

In [68]:
power_filtered['quantity'].sum()

np.float64(240580.0)

In [69]:
power[ 
    ((power['country'] == 'Latvia') | (power['country'] == 'Lithuania') | (power['country'] == 'Estonia')) & 
    ((power['category'] == 4) | (power['category'] == 12) | (power['category'] == 21)) &
    (power['quantity'] > 0) &
    ((power['year'] >= 2005) & (power['year'] <= 2010))
]['quantity'].sum()

np.float64(240580.0)